build:
  stage: build
  script:
    - dotnet restore
    - dotnet build
test:
  stage: test
  script:
    - dotnet test

stages:
  - publish

publish:
  stage: publish
  script:
    - dotnet publish -c release --no-restore
  artifacts:
    paths:
      - D:\4-Raksmey\LOL\published