image: mcr.microsoft.com/dotnet/sdk:7.0

stages:
  - build
  - test

build:
  stage: build
  script:
    - dotnet restore
    - dotnet build --configuration Release
  artifacts:
    paths:
      - ./bin/Release/net7.0/publish/

test:
  stage: test
  script:
    - dotnet test
